### ISSUE TITLE
Type Error after copying demo code to my project

### ISSUE THREAD

**Issue by whittssg** [kdietrich/gridstack-angular#12]
Hello, I copied the controller code and html code from the demo and added it to my angular app but i get the following error:

```
TypeError: this.container.closest(...).size is not a function
    at new GridStack (http://localhost:9000/bower_components/gridstack/dist/gridstack.js:511:69)
    at HTMLDivElement.<anonymous> (http://localhost:9000/bower_components/gridstack/dist/gridstack.js:1642:40)
    at Function.each (http://localhost:9000/bower_components/jquery/dist/jquery.js:359:19)
    at jQuery.each (http://localhost:9000/bower_components/jquery/dist/jquery.js:152:17)
    at jQuery.$.fn.gridstack (http://localhost:9000/bower_components/gridstack/dist/gridstack.js:1638:21)
    at init (http://localhost:9000/bower_components/gridstack-angular/dist/gridstack-angular.min.js:8:210)
    at link (http://localhost:9000/bower_components/gridstack-angular/dist/gridstack-angular.min.js:9:295)
    at http://localhost:9000/bower_components/angular/angular.js:9688:44
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:9694:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:9093:11) <div gridstack="" options="options" class="ng-isolate-scope">
```

Any idea?

i am using v0.4.0 (2016-04-08)
Thanks

**Comment by whittssg** [comment]
Never mind.. wrong version of jquery
